name: CI

on:
- push
- pull_request

jobs:
  main:
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python }}
    steps:
    - uses: actions/checkout@v3
    - name: set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: apt update
      run:
        sudo apt-get update
    - name: apt install GCC
      run:
        sudo apt-get install gcc
    - name: prepare pip
      run:
        python -m pip install --upgrade pip wheel setuptools numpy
    - name: install apt deps
      run:
        sudo apt-get install
          libjpeg-dev
          libtiff-dev
          libgtk-3-dev
          libgtk3.0
          autoconf
          build-essential
          libpng16-16
          libpng-dev
          dpkg-dev
          build-essential
    - name: build and install Gamera
      run: |
        python -m pip install --verbose .
    # The directory seems to be required, otherwise we get some errors:
    #    gamera.gamera_xml.XMLError: Cannot create a file at '/home/runner/work/gamera-4/gamera-4/tmp'
    - name: prepare tests
      run: |
        python -m pip install --upgrade pytest docutils pygments
        mkdir tmp
    - name: run tests
      run:
        pytest
